import type { Card } from '../types/game';

export const STANDARD_DECK: Omit<Card, 'id'>[] = [
  {
    type: 'move1',
    name: 'March Forward',
    description: 'Step 1 hex straight ahead in your facing direction.',
    category: 'movement',
    range: 1,
    facingMoveType: 'forward',
    iconName: 'Footprints',
    spriteUrl: 'sprites/card_icon_move1.png',
  },
  {
    type: 'move2',
    name: 'Sprint Ahead',
    description: 'Sprint 2 hexes straight ahead in your facing direction.',
    category: 'movement',
    range: 2,
    facingMoveType: 'sprint',
    iconName: 'Zap',
    spriteUrl: 'sprites/card_icon_move2.png',
  },
  {
    type: 'sidestep',
    name: 'Flank Strafe',
    description: 'Sidestep 1 hex to the side relative to your facing.',
    category: 'movement',
    range: 1,
    facingMoveType: 'sidestep_right',
    iconName: 'Move',
    spriteUrl: 'sprites/card_icon_sidestep.png',
  },
  {
    type: 'pivot_left',
    name: 'Pivot Left',
    description: 'Rotate your unit 60° counter-clockwise.',
    category: 'movement',
    range: 0,
    facingMoveType: 'pivot_left',
    turnAmount: -1,
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_pivot_left.png',
  },
  {
    type: 'pivot_right',
    name: 'Pivot Right',
    description: 'Rotate your unit 60° clockwise.',
    category: 'movement',
    range: 0,
    facingMoveType: 'pivot_right',
    turnAmount: 1,
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_pivot_right.svg',
  },
  {
    type: 'backstep',
    name: 'Tactical Retreat',
    description: 'Step 1 hex backward while maintaining your current facing.',
    category: 'movement',
    range: 1,
    facingMoveType: 'backstep',
    iconName: 'Footprints',
    spriteUrl: 'sprites/card_icon_backstep.svg',
  },
  {
    type: 'melee',
    name: 'Frontal Slash',
    description: 'Slash an enemy directly in your facing direction for 25 damage.',
    category: 'attack',
    range: 1,
    damage: 25,
    facingAttackType: 'frontal',
    iconName: 'Sword',
    spriteUrl: 'sprites/card_icon_melee.png',
  },
  {
    type: 'heavy',
    name: 'Heavy Bash',
    description: 'Deal 35 damage to enemy in front and knock them back 1 hex.',
    category: 'attack',
    range: 1,
    damage: 35,
    pushDist: 1,
    facingAttackType: 'frontal',
    iconName: 'Hammer',
    spriteUrl: 'sprites/card_icon_heavy.png',
  },
  {
    type: 'fireball',
    name: 'Flame Blast',
    description: 'Hurl a magic projectile up to 3 hexes along your facing line for 22 damage.',
    category: 'attack',
    range: 3,
    damage: 22,
    facingAttackType: 'line',
    iconName: 'Flame',
    spriteUrl: 'sprites/card_icon_fireball.png',
  },
  {
    type: 'whirlwind',
    name: 'Whirlwind',
    description: 'Slash all surrounding adjacent hexes for 16 damage.',
    category: 'attack',
    range: 1,
    damage: 16,
    facingAttackType: 'aoe',
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_whirlwind.png',
  },
  {
    type: 'shield',
    name: 'Rune Shield',
    description: 'Gain +30 Shield for this round to absorb incoming damage.',
    category: 'defense',
    range: 0,
    shield: 30,
    iconName: 'Shield',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'push',
    name: 'Force Wave',
    description: 'Push an enemy in your facing direction 2 hexes back.',
    category: 'utility',
    range: 1,
    pushDist: 2,
    facingAttackType: 'frontal',
    iconName: 'Wind',
    spriteUrl: 'sprites/card_icon_push.png',
  },
  {
    type: 'teleport',
    name: 'Blink Step',
    description: 'Instantly teleport 2 hexes forward in your facing direction.',
    category: 'movement',
    range: 2,
    facingMoveType: 'sprint',
    iconName: 'Sparkles',
    spriteUrl: 'sprites/card_icon_teleport.png',
  },
  {
    type: 'counter',
    name: 'Riposte',
    description: 'Prepare a counter-strike; deal 25 damage if attacked from the front.',
    category: 'defense',
    range: 0,
    damage: 25,
    iconName: 'ShieldAlert',
    spriteUrl: 'sprites/card_icon_counter.png',
  },
  {
    type: 'meditate',
    name: 'Second Wind',
    description: 'Recover 20 Health.',
    category: 'utility',
    range: 0,
    healAmount: 20,
    iconName: 'HeartPulse',
    spriteUrl: 'sprites/card_icon_meditate.png',
  },
];

export const DEFAULT_MOVE_CARDS: Card[] = [
  {
    id: 'move-fixed',
    type: 'move1',
    name: 'Move',
    description: 'Step 1 hex straight ahead in your facing direction.',
    category: 'movement',
    range: 1,
    facingMoveType: 'forward',
    iconName: 'Footprints',
    spriteUrl: 'sprites/card_icon_move1.png',
  },
  {
    id: 'pivot-left-fixed',
    type: 'pivot_left',
    name: 'Turn Left',
    description: 'Rotate your unit 60° left (counter-clockwise).',
    category: 'movement',
    range: 0,
    facingMoveType: 'pivot_left',
    turnAmount: -1,
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_pivot_left.png',
  },
  {
    id: 'pivot-right-fixed',
    type: 'pivot_right',
    name: 'Turn Right',
    description: 'Rotate your unit 60° right (clockwise).',
    category: 'movement',
    range: 0,
    facingMoveType: 'pivot_right',
    turnAmount: 1,
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_pivot_right.svg',
  },
];

export function shuffleDeck(cards: Card[]): Card[] {
  const shuffled = [...cards];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function createStandardPlayerDeck(): Card[] {
  return STANDARD_DECK.map((template, idx) => ({
    ...template,
    id: `${template.type}-${idx}-${Math.random().toString(36).substring(2, 7)}`,
  }));
}

