import type { Card } from '../types/game';

export const STANDARD_DECK: Omit<Card, 'id'>[] = [
  {
    type: 'melee',
    name: 'Frontal Slash',
    description: 'Slash an enemy directly in your facing direction for 25 damage.',
    category: 'attack',
    range: 1,
    damage: 25,
    facingAttackType: 'frontal',
    iconName: 'Sword',
    spriteUrl: 'sprites/card_icon_melee.png',
  },
  {
    type: 'heavy',
    name: 'Heavy Bash',
    description: 'Deal 35 damage to enemy in front and knock them back 1 hex.',
    category: 'attack',
    range: 1,
    damage: 35,
    pushDist: 1,
    facingAttackType: 'frontal',
    iconName: 'Hammer',
    spriteUrl: 'sprites/card_icon_heavy.png',
  },
  {
    type: 'fireball',
    name: 'Flame Blast',
    description: 'Hurl a magic projectile up to 3 hexes along your facing line for 22 damage.',
    category: 'attack',
    range: 3,
    damage: 22,
    facingAttackType: 'line',
    iconName: 'Flame',
    spriteUrl: 'sprites/card_icon_fireball.png',
  },
  {
    type: 'whirlwind',
    name: 'Whirlwind',
    description: 'Slash all surrounding adjacent hexes for 16 damage.',
    category: 'attack',
    range: 1,
    damage: 16,
    facingAttackType: 'aoe',
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_whirlwind.png',
  },
  {
    type: 'shield',
    name: 'Rune Shield',
    description: 'Gain +30 Shield for this round to absorb incoming damage.',
    category: 'defense',
    range: 0,
    shield: 30,
    iconName: 'Shield',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'push',
    name: 'Force Wave',
    description: 'Push an enemy in your facing direction 2 hexes back.',
    category: 'utility',
    range: 1,
    pushDist: 2,
    facingAttackType: 'frontal',
    iconName: 'Wind',
    spriteUrl: 'sprites/card_icon_push.png',
  },
  {
    type: 'counter',
    name: 'Riposte',
    description: 'Prepare a counter-strike; deal 25 damage if attacked from the front.',
    category: 'defense',
    range: 0,
    damage: 25,
    iconName: 'ShieldAlert',
    spriteUrl: 'sprites/card_icon_counter.png',
  },
  {
    type: 'meditate',
    name: 'Second Wind',
    description: 'Recover 20 Health.',
    category: 'utility',
    range: 0,
    healAmount: 20,
    iconName: 'HeartPulse',
    spriteUrl: 'sprites/card_icon_meditate.png',
  },
  {
    type: 'thunder',
    name: 'Thunder Bolt',
    description: 'Strike target up to 2 hexes away for 28 damage.',
    category: 'attack',
    range: 2,
    damage: 28,
    facingAttackType: 'line',
    iconName: 'Zap',
    spriteUrl: 'sprites/card_icon_fireball.png',
  },
  {
    type: 'iron_wall',
    name: 'Fortress Aegis',
    description: 'Gain +45 Shield to withstand heavy incoming damage.',
    category: 'defense',
    range: 0,
    shield: 45,
    iconName: 'ShieldAlert',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'frost_nova',
    name: 'Frost Burst',
    description: 'Erupt an icy blast hitting all adjacent hexes for 20 damage.',
    category: 'attack',
    range: 1,
    damage: 20,
    facingAttackType: 'aoe',
    iconName: 'Sparkles',
    spriteUrl: 'sprites/card_icon_whirlwind.png',
  },
  {
    type: 'vampiric',
    name: 'Vampiric Strike',
    description: 'Slash enemy for 24 damage while siphoning 10 Health.',
    category: 'attack',
    range: 1,
    damage: 24,
    healAmount: 10,
    facingAttackType: 'frontal',
    iconName: 'Sword',
    spriteUrl: 'sprites/card_icon_melee.png',
  },
  // --- 20 NEW ABILITY CARDS ---
  // 1. Movement & Positioning (Pulls & Displacement)
  {
    type: 'scorpion_pull',
    name: 'Harpoon Whip',
    description: 'Get over here! Drag an enemy up to 3 hexes away straight into your melee range.',
    category: 'utility',
    range: 3,
    pullDist: 2,
    facingAttackType: 'line',
    iconName: 'Wind',
    spriteUrl: 'sprites/card_icon_push.png',
  },
  {
    type: 'hook_shot',
    name: 'Grappling Hook',
    description: 'Latch onto an enemy up to 3 hexes away, pulling them 1 hex towards you and dealing 15 damage.',
    category: 'attack',
    range: 3,
    damage: 15,
    pullDist: 1,
    facingAttackType: 'line',
    iconName: 'Zap',
    spriteUrl: 'sprites/card_icon_fireball.png',
  },
  {
    type: 'gravitational_surge',
    name: 'Vortex Pull',
    description: 'Unleash a magnetic vortex pulling all enemies in a 2-hex radius 1 hex closer to you.',
    category: 'utility',
    range: 2,
    pullDist: 1,
    facingAttackType: 'aoe',
    iconName: 'Sparkles',
    spriteUrl: 'sprites/card_icon_whirlwind.png',
  },
  {
    type: 'swap_strike',
    name: 'Shadow Transposition',
    description: 'Swap locations with an enemy target 2 hexes ahead and slash them for 18 damage.',
    category: 'attack',
    range: 2,
    damage: 18,
    pullDist: 2,
    facingAttackType: 'line',
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_melee.png',
  },
  {
    type: 'repulsion_blast',
    name: 'Graviton Blast',
    description: 'Blast all surrounding enemies dealing 18 damage and knocking them back 2 hexes.',
    category: 'attack',
    range: 1,
    damage: 18,
    pushDist: 2,
    facingAttackType: 'aoe',
    iconName: 'Wind',
    spriteUrl: 'sprites/card_icon_push.png',
  },
  // 2. High-Impact AOE Abilities
  {
    type: 'chain_lightning',
    name: 'Chain Lightning',
    description: 'Zap all foes in front up to 3 hexes away with electric arcs for 26 damage.',
    category: 'attack',
    range: 3,
    damage: 26,
    facingAttackType: 'line',
    iconName: 'Zap',
    spriteUrl: 'sprites/card_icon_fireball.png',
  },
  {
    type: 'blasphemous_burst',
    name: 'Cleave Arc',
    description: 'Sweep your weapon in a 180° arc hitting 3 frontal hexes for 28 damage.',
    category: 'attack',
    range: 1,
    damage: 28,
    facingAttackType: 'cleave_arc',
    iconName: 'Sword',
    spriteUrl: 'sprites/card_icon_melee.png',
  },
  {
    type: 'supernova',
    name: 'Supernova',
    description: 'Detonate a massive fiery explosion around you, dealing 32 damage to all adjacent hexes.',
    category: 'attack',
    range: 1,
    damage: 32,
    facingAttackType: 'aoe',
    iconName: 'Flame',
    spriteUrl: 'sprites/card_icon_fireball.png',
  },
  {
    type: 'seismic_slam',
    name: 'Seismic Slam',
    description: 'Slam the ground! Deal 24 damage and push all adjacent enemies 1 hex away.',
    category: 'attack',
    range: 1,
    damage: 24,
    pushDist: 1,
    facingAttackType: 'aoe',
    iconName: 'Hammer',
    spriteUrl: 'sprites/card_icon_heavy.png',
  },
  {
    type: 'blade_storm',
    name: 'Blade Storm',
    description: 'Spin wildly hitting all foes within 2 hexes for 22 damage.',
    category: 'attack',
    range: 2,
    damage: 22,
    facingAttackType: 'aoe',
    iconName: 'Sparkles',
    spriteUrl: 'sprites/card_icon_whirlwind.png',
  },
  // 3. Defensive Abilities & Warding
  {
    type: 'parry_dash',
    name: 'Parry & Stance',
    description: 'Raise a defensive guard (+25 Shield) while instantly counter-pivoting 180°.',
    category: 'defense',
    range: 0,
    shield: 25,
    turnAmount: 3,
    iconName: 'ShieldAlert',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'reflection_barrier',
    name: 'Mirror Shield',
    description: 'Erect an impenetrable barrier (+50 Shield) to absorb heavy combat incoming damage.',
    category: 'defense',
    range: 0,
    shield: 50,
    iconName: 'Shield',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'sanctuary',
    name: 'Sacred Sanctuary',
    description: 'Channel holy magic to instantly heal 35 HP.',
    category: 'defense',
    range: 0,
    healAmount: 35,
    iconName: 'HeartPulse',
    spriteUrl: 'sprites/card_icon_meditate.png',
  },
  {
    type: 'spectral_shield',
    name: 'Spectral Shield',
    description: 'Gain +20 Shield and restore 15 HP simultaneously.',
    category: 'defense',
    range: 0,
    shield: 20,
    healAmount: 15,
    iconName: 'Shield',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  // 4. Round-Long Buffs & Stances
  {
    type: 'berserk_fury',
    name: 'Berserker Stance',
    description: 'Infuse yourself with raw fury! Gain +15 Damage on all attacks for 2 full rounds.',
    category: 'utility',
    range: 0,
    buffType: 'attackBoost',
    buffDuration: 2,
    buffValue: 15,
    iconName: 'Flame',
    spriteUrl: 'sprites/card_icon_fireball.png',
  },
  {
    type: 'overcharge',
    name: 'Overcharge',
    description: 'Surge with electric energy! Instantly gain +20 Shield and +10 Attack Damage for 2 rounds.',
    category: 'utility',
    range: 0,
    shield: 20,
    buffType: 'attackBoost',
    buffDuration: 2,
    buffValue: 10,
    iconName: 'Zap',
    spriteUrl: 'sprites/card_icon_fireball.png',
  },
  {
    type: 'shadow_cloak',
    name: 'Shadow Cloak',
    description: 'Wrap in dark mist to gain +10 HP regeneration per round for 3 rounds.',
    category: 'utility',
    range: 0,
    buffType: 'healRegen',
    buffDuration: 3,
    buffValue: 10,
    iconName: 'Sparkles',
    spriteUrl: 'sprites/card_icon_meditate.png',
  },
  {
    type: 'titan_fortitude',
    name: 'Titan Fortitude',
    description: 'Harden your armor to gain +10 Shield regen at the start of every round for 3 rounds.',
    category: 'defense',
    range: 0,
    shield: 25,
    buffType: 'shield',
    buffDuration: 3,
    buffValue: 10,
    iconName: 'ShieldAlert',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'bounty_hunter',
    name: 'War Cry',
    description: 'Shout a battle cry! Deal 15 damage in a 360° blast and gain +10 Attack Damage for 2 rounds.',
    category: 'attack',
    range: 1,
    damage: 15,
    buffType: 'attackBoost',
    buffDuration: 2,
    buffValue: 10,
    facingAttackType: 'aoe',
    iconName: 'Flame',
    spriteUrl: 'sprites/card_icon_whirlwind.png',
  },
  {
    type: 'blood_pact',
    name: 'Blood Pact',
    description: 'Sacrifice 10 HP to empower yourself with +20 Attack Damage for 2 full rounds!',
    category: 'utility',
    range: 0,
    healAmount: -10,
    buffType: 'attackBoost',
    buffDuration: 2,
    buffValue: 20,
    iconName: 'Flame',
    spriteUrl: 'sprites/card_icon_fireball.png',
  },
  // --- 10 ANTI-BUMP & UNYIELDING ABILITIES ---
  {
    type: 'anchor_stance',
    name: 'Anchor Stance',
    description: 'Dig in! Plant your feet for this turn slot; cannot be bumped or pushed by any moving enemy.',
    category: 'defense',
    range: 0,
    shield: 15,
    isUnyieldingSlot: true,
    iconName: 'ShieldAlert',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'juggernaut_aura',
    name: 'Juggernaut Aura',
    description: 'Become an unmovable juggernaut! Immune to all bumps and knockbacks for 2 full rounds.',
    category: 'utility',
    range: 0,
    buffType: 'unyielding',
    buffDuration: 2,
    buffValue: 1,
    iconName: 'Shield',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'iron_roots',
    name: 'Iron Roots',
    description: 'Root yourself deep in the soil (+20 Shield) and become immune to all bumps for 3 full rounds.',
    category: 'defense',
    range: 0,
    shield: 20,
    buffType: 'unyielding',
    buffDuration: 3,
    buffValue: 1,
    iconName: 'ShieldAlert',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'spiked_bulwark',
    name: 'Spiked Bulwark',
    description: 'Gain +25 Shield and slot anti-bump immunity. If an enemy tries to bump you, they take 20 recoil damage!',
    category: 'defense',
    range: 0,
    shield: 25,
    isUnyieldingSlot: true,
    iconName: 'ShieldAlert',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'immovable_wall',
    name: 'Immovable Wall',
    description: 'Gain massive +40 Shield and full bump immunity for 1 full round.',
    category: 'defense',
    range: 0,
    shield: 40,
    buffType: 'unyielding',
    buffDuration: 1,
    buffValue: 1,
    iconName: 'Shield',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'shockwave_repel',
    name: 'Shockwave Repel',
    description: 'Blast a counter-wave around you (15 DMG, 1-hex push) and gain slot bump immunity.',
    category: 'attack',
    range: 1,
    damage: 15,
    pushDist: 1,
    facingAttackType: 'aoe',
    isUnyieldingSlot: true,
    iconName: 'Wind',
    spriteUrl: 'sprites/card_icon_whirlwind.png',
  },
  {
    type: 'counter_bump',
    name: 'Spike Stance',
    description: 'Prepare a counter-stance; gain slot bump immunity and deal 25 damage to any frontal attacker.',
    category: 'defense',
    range: 0,
    damage: 25,
    isUnyieldingSlot: true,
    iconName: 'ShieldAlert',
    spriteUrl: 'sprites/card_icon_counter.png',
  },
  {
    type: 'kinetic_absorber',
    name: 'Kinetic Absorber',
    description: 'Absorb kinetic force! Gain slot bump immunity; if an enemy tries to bump you, gain +20 Shield.',
    category: 'defense',
    range: 0,
    shield: 15,
    isUnyieldingSlot: true,
    iconName: 'Shield',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'stone_footing',
    name: 'Stone Footing',
    description: 'Fortify your lower stance (+10 Shield & +15 HP heal) while gaining bump immunity for 2 rounds.',
    category: 'utility',
    range: 0,
    shield: 10,
    healAmount: 15,
    buffType: 'unyielding',
    buffDuration: 2,
    buffValue: 1,
    iconName: 'HeartPulse',
    spriteUrl: 'sprites/card_icon_meditate.png',
  },
  {
    type: 'unyielding_bastion',
    name: 'Unyielding Bastion',
    description: 'Ultimate stance: Gain +30 Shield, +10 Attack Damage, and complete bump immunity for 2 full rounds!',
    category: 'utility',
    range: 0,
    shield: 30,
    buffType: 'unyielding',
    buffDuration: 2,
    buffValue: 1,
    iconName: 'Sparkles',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  // --- 10 NEW ADVANCED MOVEMENT ABILITIES ---
  {
    type: 'dash_forward',
    name: 'Kinetic Dash',
    description: 'Dash 2 hexes straight forward along your facing direction, bypassing ground hazards.',
    category: 'movement',
    range: 2,
    facingMoveType: 'sprint',
    iconName: 'Zap',
    spriteUrl: 'sprites/card_icon_move1.png',
  },
  {
    type: 'sidestep_evasion',
    name: 'Tactical Sidestep',
    description: 'Strafe 1 hex to your right without changing facing, dodging incoming frontal line attacks.',
    category: 'movement',
    range: 1,
    facingMoveType: 'sidestep_right',
    iconName: 'Footprints',
    spriteUrl: 'sprites/card_icon_move1.png',
  },
  {
    type: 'ghost_strafe',
    name: 'Ghost Strafe',
    description: 'Sidestep 1 hex to your left while retaining your forward facing direction.',
    category: 'movement',
    range: 1,
    facingMoveType: 'sidestep_left',
    iconName: 'Footprints',
    spriteUrl: 'sprites/card_icon_move1.png',
  },
  {
    type: 'backflip_vault',
    name: 'Vault Backwards',
    description: 'Leap backwards 1 hex while maintaining forward weapon orientation.',
    category: 'movement',
    range: 1,
    facingMoveType: 'backstep',
    iconName: 'Footprints',
    spriteUrl: 'sprites/card_icon_move1.png',
  },
  {
    type: 'shadow_step',
    name: 'Shadow Step',
    description: 'Instantly teleport behind the nearest rival Commander (prioritizing targets in front).',
    category: 'movement',
    range: 4,
    facingMoveType: 'teleport_nearest',
    iconName: 'Sparkles',
    spriteUrl: 'sprites/card_icon_push.png',
  },
  {
    type: 'phase_blink',
    name: 'Phase Blink',
    description: 'Teleport 2 hexes forward straight ahead, phasing directly through obstacles & units.',
    category: 'movement',
    range: 2,
    facingMoveType: 'phase_step',
    iconName: 'Sparkles',
    spriteUrl: 'sprites/card_icon_move1.png',
  },
  {
    type: 'bulwark_charge',
    name: 'Bulwark Charge',
    description: 'Rush 2 hexes forward and deal 25 damage to the first enemy hit.',
    category: 'movement',
    range: 2,
    damage: 25,
    facingMoveType: 'sprint',
    facingAttackType: 'frontal',
    iconName: 'Sword',
    spriteUrl: 'sprites/card_icon_melee.png',
  },
  {
    type: 'tumble_roll',
    name: 'Tumble Roll',
    description: 'Roll 1 hex forward and turn 180° around to face your previous position.',
    category: 'movement',
    range: 1,
    facingMoveType: 'roll_flip',
    turnAmount: 3,
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_about_face.svg',
  },
  {
    type: 'sky_vault',
    name: 'Sky Vault',
    description: 'Leap 2 hexes forward over adjacent units while raising a +15 Shield barrier.',
    category: 'movement',
    range: 2,
    shield: 15,
    facingMoveType: 'sprint',
    iconName: 'Shield',
    spriteUrl: 'sprites/card_icon_shield.png',
  },
  {
    type: 'warp_leap',
    name: 'Warp Leap',
    description: 'Warp 3 hexes straight ahead along your facing line to rapidly close down distance.',
    category: 'movement',
    range: 3,
    facingMoveType: 'sprint',
    iconName: 'Wind',
    spriteUrl: 'sprites/card_icon_move1.png',
  },
];

export const DEFAULT_MOVE_CARDS: Card[] = [
  {
    id: 'move-fixed',
    type: 'move1',
    name: 'Move',
    description: 'Step 1 hex straight ahead in your facing direction.',
    category: 'movement',
    range: 1,
    facingMoveType: 'forward',
    iconName: 'Footprints',
    spriteUrl: 'sprites/card_icon_move1.png',
  },
  {
    id: 'pivot-left-fixed',
    type: 'pivot_left',
    name: 'Turn Left',
    description: 'Rotate your unit 60° left (counter-clockwise).',
    category: 'movement',
    range: 0,
    facingMoveType: 'pivot_left',
    turnAmount: -1,
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_pivot_left.png',
  },
  {
    id: 'pivot-right-fixed',
    type: 'pivot_right',
    name: 'Turn Right',
    description: 'Rotate your unit 60° right (clockwise).',
    category: 'movement',
    range: 0,
    facingMoveType: 'pivot_right',
    turnAmount: 1,
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_pivot_right.svg',
  },
  {
    id: 'about-face-fixed',
    type: 'about_face',
    name: '180 Flip',
    description: 'Turn around 180° (about face).',
    category: 'movement',
    range: 0,
    facingMoveType: 'about_face',
    turnAmount: 3,
    iconName: 'RotateCw',
    spriteUrl: 'sprites/card_icon_about_face.svg',
  },
  {
    id: 'attack-fixed',
    type: 'attack',
    name: 'Attack',
    description: 'Strike the enemy hex directly in front of you for 20 damage.',
    category: 'attack',
    range: 1,
    damage: 20,
    facingAttackType: 'frontal',
    iconName: 'Sword',
    spriteUrl: 'sprites/card_icon_melee.png',
  },
];

export function shuffleDeck(cards: Card[]): Card[] {
  const shuffled = [...cards];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function createStandardPlayerDeck(): Card[] {
  return STANDARD_DECK.map((template, idx) => ({
    ...template,
    id: `${template.type}-${idx}-${Math.random().toString(36).substring(2, 7)}`,
  }));
}

